apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: google-scripts
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: google-scripts
subjects:
- kind: ServiceAccount
  name: default
  namespace: default #change this to your desired namespace
roleRef:
  kind: ClusterRole
  name: google-scripts
  apiGroup: rbac.authorization.k8s.io

